'use client';

import { useEffect, useState } from 'react';
import { HelpCircle, ChevronDown, User, Briefcase, Building2, BookOpen } from 'lucide-react';
import { getMe } from '../api';

export default function HelpPage() {
  const [userInfo, setUserInfo] = useState<any>(null);
  const [openSection, setOpenSection] = useState<string | null>(null);

  useEffect(() => {
    getMe().then(res => setUserInfo(res.data)).catch(console.error);
  }, []);

  if (!userInfo) return <div className="p-8 text-center text-sm opacity-50">Loading Guide...</div>;

  const role = userInfo.role || 'EMPLOYEE';

  const sections = {
    EMPLOYEE: [
      {
        id: 'emp-feed',
        title: 'Using the Social Feed',
        content: 'The Feed allows you to share updates, celebrate wins, and communicate with colleagues across the entire enterprise. You can create text posts, share images, and like other users\' posts to increase engagement.'
      },
      {
        id: 'emp-profile',
        title: 'Managing Your Profile',
        content: 'Your Profile is your digital resume within the enterprise. Keep your skills, education, and experience updated. This information is used by the internal talent matching engine if you ever apply for a transfer.'
      },
      {
        id: 'emp-trading',
        title: 'Applying for Talent Transfer',
        content: 'The Talent Trading Window allows you to request an internal transfer to another organisation or department. Navigate to the Trading tab, select your target organisation, and submit a request. Your eligibility will be evaluated instantly by the Rule Engine based on tenure and performance.'
      }
    ],
    HR: [
      {
        id: 'hr-directory',
        title: 'Employee Directory & AI Insights',
        content: 'The Directory gives you a unified view of all employees in your organisation. Click on an employee to view their detailed retention risk profile, generated by our Machine Learning model. The Gemini AI Copilot will provide a full breakdown of their flight risk.'
      },
      {
        id: 'hr-upload',
        title: 'Bulk Uploading Employees',
        content: 'Use the Upload panel to import a CSV of employee data. Ensure your CSV matches the required headers (age, salary, yearsAtCompany, performanceRating, etc.). The Machine Learning model will automatically score every imported employee.'
      },
      {
        id: 'hr-trading',
        title: 'Managing Transfer Requests',
        content: 'In the Trading Window, you can configure your Organisation\'s transfer policies (min tenure, performance requirements). You also monitor the Approval Pipeline to approve or reject incoming/outgoing talent transfer requests.'
      }
    ],
    ORGANISATION: [
      {
        id: 'org-dashboard',
        title: 'Organisation Overview',
        content: 'The primary dashboard provides high-level metrics on retention risk, headcount, and enterprise health. It helps you identify high-risk departments before attrition occurs.'
      },
      {
        id: 'org-trading',
        title: 'Configuring Transfer Policies',
        content: 'As an Organisation Admin, you control the Trading Window Policy. In the Trading panel, you can set the Start/End dates for the transfer window, and enforce strict minimum tenure and performance thresholds for anyone requesting to transfer out.'
      },
      {
        id: 'org-network',
        title: 'Enterprise Network',
        content: 'The Organisation tab allows you to manage connections with partner organisations. You can send connection requests to collaborate on joint talent mobility initiatives.'
      }
    ]
  };

  const currentSections = sections[role as keyof typeof sections] || sections['EMPLOYEE'];

  return (
    <div className="mx-auto max-w-4xl space-y-8 animate-fade-in py-4">
      {/* Header */}
      <div className="flex flex-col items-center text-center space-y-4 mb-12">
        <div className="p-4 rounded-2xl shadow-[0_0_30px_var(--accent-glow)]" style={{ backgroundColor: 'var(--accent)', color: '#000' }}>
          <BookOpen size={40} />
        </div>
        <div>
          <h1 className="text-3xl font-black tracking-tight" style={{ color: 'var(--text-primary)' }}>Enterprise Help Center</h1>
          <p className="mt-2 text-sm max-w-lg mx-auto leading-relaxed" style={{ color: 'var(--text-muted)' }}>
            Welcome to your personalized guide. Below you will find detailed explanations of the features available to your specific role 
            <strong className="ml-1 px-2 py-0.5 rounded-full text-xs bg-[var(--bg-card)] border border-[var(--border-subtle)] text-[var(--text-primary)]">
              {role}
            </strong>
          </p>
        </div>
      </div>

      {/* Accordion List */}
      <div className="space-y-4">
        {currentSections.map((section) => (
          <div 
            key={section.id} 
            className="rounded-2xl border transition-all duration-200 overflow-hidden" 
            style={{ 
              backgroundColor: 'var(--bg-surface)', 
              borderColor: openSection === section.id ? 'var(--accent)' : 'var(--border-subtle)' 
            }}
          >
            <button
              onClick={() => setOpenSection(openSection === section.id ? null : section.id)}
              className="w-full flex items-center justify-between p-5 text-left focus:outline-none hover:bg-[var(--bg-base)] transition-colors"
            >
              <h3 className="font-bold text-sm" style={{ color: openSection === section.id ? 'var(--accent)' : 'var(--text-primary)' }}>
                {section.title}
              </h3>
              <ChevronDown 
                size={18} 
                className={`transition-transform duration-300 ${openSection === section.id ? 'rotate-180 text-[var(--accent)]' : 'text-[var(--text-muted)]'}`} 
              />
            </button>
            
            <div 
              className={`transition-all duration-300 ease-in-out ${openSection === section.id ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'}`}
            >
              <div className="p-5 pt-0 text-sm leading-relaxed border-t border-[var(--border-subtle)] mt-2" style={{ color: 'var(--text-muted)' }}>
                {section.content}
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-12 p-6 rounded-2xl border border-dashed text-center space-y-2" style={{ borderColor: 'var(--border-subtle)', backgroundColor: 'var(--bg-base)' }}>
        <HelpCircle size={24} className="mx-auto text-[var(--text-muted)] mb-3" />
        <h4 className="font-bold text-sm text-[var(--text-primary)]">Still need help?</h4>
        <p className="text-xs text-[var(--text-muted)]">If you encounter issues, please contact your Enterprise System Administrator.</p>
      </div>
    </div>
  );
}
